### ISSUE TITLE
package required for compute service

### ISSUE THREAD

**Issue by geemus** [fastly/terraform-provider-fastly#728]
### Affected Fastly Terraform Resource(s)

Please list the affected resources, for example:

- `fastly_service_compute`

### Expected Behavior

In the web UI, package is not a required attribute while creating a new compute service. We are (at least currently) planning to use terraform to manage the creation/destruction of our services and resources, but utilize CI/CD to manage the packaging. As such, we would prefer NOT to be required to provide a package at creation time here.

### Actual Behavior

Package is required, so we needed to create a placeholder and push that along with service creation (as well as ensuring anyone running terraform has this file around if they need to update things). We also needed to add:
```
  lifecycle {
    ignore_changes = [
      package,
    ]
  }
```

### Steps to Reproduce

Create a tf file with a `fastly_service_compute` resource, omitting the package block, and run `terraform apply`

**Comment by Integralist** [comment]
Hi @geemus 

Thanks for opening this issue.

Your request to have granular control over _when_ the package should be provided makes sense to me.

So I'll open a ticket internally to track this request.

I can't give an estimate for when that work would be started/completed but just be aware that the default Terraform behaviour is to activate the service (e.g. `activate` defaults to `true`). This means if we make the change so that `package` is optional, you would need to ensure your service sets `activate = false` to prevent Terraform from trying to call the Fastly API to activate the service (as that call will fail if there is no package uploaded to the service).

**Comment by geemus** [comment]
Sounds good, and thanks for the clarification. I think that should work fine for us, we were leaning toward having github actions manage the deploys/etc (as that is how we manage our other deploys, this seems most consistent and easy to reason about). I'll keep in mind that this may need to require an activation somewhere in the mix.

**Comment by Integralist** [comment]
👋🏻 @geemus 

Just a quick update to say I have a PR waiting review (feel free to have a look):
https://github.com/fastly/terraform-provider-fastly/pull/733

**Comment by geemus** [comment]
LGTM, thanks!

**Comment by Integralist** [comment]
@geemus I've merged the PR but just a 'heads up' that I have a few other things I need to work on for Terraform before I can publish the next release (so nothing will be released just yet).

**Comment by geemus** [comment]
@Integralist - sure, makes sense.

We'll keep an eye out for the release (I think dependabot should catch it if we don't first).

**Comment by Integralist** [comment]
https://github.com/fastly/terraform-provider-fastly/releases/tag/v5.4.0

**Comment by marceloboeira** [comment]
I've faced this issue too, still happens if you try to get around not manually managing the `activate` and `package` fields. 

I've went around it this way, Maybe useful to others...

```hcl
locals {
  activate = [
    false, # During creation, set activate to false
    true,  # During update, set activate to true
  ]
}

resource "fastly_service_compute" "this" {
  count = 1
  name = var.name

  # Hack to ensure activate is set to the correct values all the times
  # Since the package is not managed by Terraform, we need to ensure that the activate value is set correctly
  # When we create, since we create without a package it needs to be set to false
  # When we update, since the package has been deployed externally we need to set it to true
  # https://github.com/fastly/terraform-provider-fastly/issues/728
  activate = local.activate[count.index]

  domain {
    name    = var.domain
    comment = "Managed by Terraform"
  }

  force_destroy = true

  # Ignore changes to the package
  lifecycle {
    ignore_changes = [
      activate,
      package,
    ]
  }
}
```
